name: 'API - Build and Publish to Docker Hub'

on:
  workflow_call:
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

jobs:
  api_build_and_publish:
    name: API - Build and Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install Dependencies
        run: yarn

      - name: Install NX
        run: yarn global add @nrwl/cli

      - name: Build API
        run: nx run api:build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push API
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hydro-garden-api:latest
